-- =============================================================================
-- Livantaa — Contact Us Module Database Schema
-- =============================================================================
-- Run this file against your MySQL / MariaDB instance:
--   mysql -u root -p livantaa < api/database/schema.sql
--
-- Or from phpMyAdmin: create a database named "livantaa" then import this file.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS `livantaa`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `livantaa`;

-- -----------------------------------------------------------------------------
-- 1. admin_users
-- Stores admin accounts. Passwords are Argon2id hashes (PHP password_hash).
-- Two seed rows are inserted below with default password "password123".
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id`            INT UNSIGNED    NOT NULL AUTO_INCREMENT,
  `name`          VARCHAR(120)    NOT NULL,
  `email`         VARCHAR(255)    NOT NULL,
  `password_hash` VARCHAR(255)    NOT NULL,
  `is_active`     TINYINT(1)      NOT NULL DEFAULT 1,
  `created_at`    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- 2. password_reset_tokens
-- One-time tokens for the Forgot Password flow. Tokens expire in 1 hour.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `password_reset_tokens` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_id`   INT UNSIGNED NOT NULL,
  `token`      VARCHAR(64)  NOT NULL,
  `expires_at` DATETIME     NOT NULL,
  `used`       TINYINT(1)   NOT NULL DEFAULT 0,
  `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_reset_token` (`token`),
  CONSTRAINT `fk_prt_admin` FOREIGN KEY (`admin_id`)
    REFERENCES `admin_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- 3. contact_submissions
-- Every public contact form submission. Status tracks the full lifecycle.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact_submissions` (
  `id`           INT UNSIGNED                                                   NOT NULL AUTO_INCREMENT,
  `name`         VARCHAR(120)                                                   NOT NULL,
  `email`        VARCHAR(255)                                                   NOT NULL,
  `phone`        VARCHAR(30)                                                    NOT NULL DEFAULT '',
  `subject`      VARCHAR(255)                                                   NOT NULL DEFAULT '',
  `message`      TEXT                                                           NOT NULL,
  `status`       ENUM('new','in_progress','contacted','resolved','closed')      NOT NULL DEFAULT 'new',
  `admin_notes`  TEXT                                                           NULL,
  `submitted_at` DATETIME                                                       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`   DATETIME                                                       NOT NULL DEFAULT CURRENT_TIMESTAMP
                                                                                   ON UPDATE CURRENT_TIMESTAMP,
  `updated_by`   INT UNSIGNED                                                   NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status`       (`status`),
  KEY `idx_submitted_at` (`submitted_at`),
  CONSTRAINT `fk_cs_admin` FOREIGN KEY (`updated_by`)
    REFERENCES `admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Seed data
-- =============================================================================

-- Admin users — password is "password123" (Argon2id hash, generated by PHP).
-- To regenerate:  php -r "echo password_hash('password123', PASSWORD_ARGON2ID);"
INSERT INTO `admin_users` (`name`, `email`, `password_hash`, `is_active`) VALUES
  (
    'Admin One',
    'admin1@livantaa.in',
    '$argon2id$v=19$m=65536,t=4,p=1$VGlmRFlCL3Fia1ZIMDU2Mw$LQBTo5IW/xGy/RqvlvmOoQvyq5XGyUn7LaRW/Q1Sqy0',
    1
  ),
  (
    'Admin Two',
    'admin2@livantaa.in',
    '$argon2id$v=19$m=65536,t=4,p=1$VGlmRFlCL3Fia1ZIMDU2Mw$LQBTo5IW/xGy/RqvlvmOoQvyq5XGyUn7LaRW/Q1Sqy0',
    1
  );
